//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPortal.DataContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SuicideDataEntities : DbContext
    {
        public SuicideDataEntities()
            : base("name=SuicideDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_AgeGroup> Tbl_AgeGroup { get; set; }
        public virtual DbSet<Tbl_Gender> Tbl_Gender { get; set; }
        public virtual DbSet<Tbl_MasterDetail> Tbl_MasterDetail { get; set; }
        public virtual DbSet<Tbl_State> Tbl_State { get; set; }
        public virtual DbSet<Tbl_SuicideCount> Tbl_SuicideCount { get; set; }
    }
}
