//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_MasterDetail
    {
        public int masterID { get; set; }
        public int surveyYear { get; set; }
        public int stateID { get; set; }
        public int genderId { get; set; }
        public int ageGroupID { get; set; }
    
        public virtual Tbl_AgeGroup Tbl_AgeGroup { get; set; }
        public virtual Tbl_Gender Tbl_Gender { get; set; }
        public virtual Tbl_State Tbl_State { get; set; }
    }
}
