//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataPortal.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gender()
        {
            this.Tbl_MasterDetail = new HashSet<Tbl_MasterDetail>();
        }
    
        public int genderID { get; set; }
        public string genderType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_MasterDetail> Tbl_MasterDetail { get; set; }
    }
}
